var h=void 0,i=!0,j=null,l=!1,n,q=this;function r(){}
function s(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){var b=s(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function v(a){return"function"==s(a)}function aa(a){var b=typeof a;return"object"==b&&a!=j||"function"==b}var x="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ba=0;function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return y.apply(j,arguments)}var ea=Date.now||function(){return+new Date};
function A(a,b){function c(){}c.prototype=b.prototype;a.Z=b.prototype;a.prototype=new c};function B(a){Error.captureStackTrace?Error.captureStackTrace(this,B):this.stack=Error().stack||"";a&&(this.message=""+a)}A(B,Error);B.prototype.name="CustomError";function ga(a){if(!ha.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ia,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ja,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ka,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(la,"&quot;"));return a}var ia=/&/g,ja=/</g,ka=/>/g,la=/\"/g,ha=/[&<>\"]/;var C=Array.prototype,ma=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},na=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},oa=C.map?function(a,b,c){return C.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),e=u(a)?a.split(""):
a,g=0;g<d;g++)g in e&&(f[g]=b.call(c,e[g],g,a));return f},pa=C.some?function(a,b,c){return C.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return i;return l};function qa(a){return C.concat.apply(C,arguments)}function ra(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function sa(a,b,c){return 2>=arguments.length?C.slice.call(a,b):C.slice.call(a,b,c)};var D,ta,E,ua;function va(){return q.navigator?q.navigator.userAgent:j}ua=E=ta=D=l;var wa;if(wa=va()){var xa=q.navigator;D=0==wa.indexOf("Opera");ta=!D&&-1!=wa.indexOf("MSIE");E=!D&&-1!=wa.indexOf("WebKit");ua=!D&&!E&&"Gecko"==xa.product}var ya=D,F=ta,G=ua,H=E,za;
a:{var Aa="",I;if(ya&&q.opera)var Ba=q.opera.version,Aa="function"==typeof Ba?Ba():Ba;else if(G?I=/rv\:([^\);]+)(\)|;)/:F?I=/MSIE\s+([^\);]+)(\)|;)/:H&&(I=/WebKit\/(\S+)/),I)var Ca=I.exec(va()),Aa=Ca?Ca[1]:"";if(F){var Da,Ea=q.document;Da=Ea?Ea.documentMode:h;if(Da>parseFloat(Aa)){za=""+Da;break a}}za=Aa}var Fa={};
function J(a){var b;if(!(b=Fa[a])){b=0;for(var c=(""+za).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",k=d[e]||"",m=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var w=m.exec(g)||["","",""],o=p.exec(k)||["","",""];if(0==w[0].length&&0==o[0].length)break;b=((0==w[1].length?0:parseInt(w[1],10))<(0==o[1].length?0:parseInt(o[1],10))?-1:(0==w[1].length?0:parseInt(w[1],
10))>(0==o[1].length?0:parseInt(o[1],10))?1:0)||((0==w[2].length)<(0==o[2].length)?-1:(0==w[2].length)>(0==o[2].length)?1:0)||(w[2]<o[2]?-1:w[2]>o[2]?1:0)}while(0==b)}b=Fa[a]=0<=b}return b}var Ga={};function Ha(){return Ga[9]||(Ga[9]=F&&!!document.documentMode&&9<=document.documentMode)};var Ia=!F||Ha();!G&&!F||F&&Ha()||G&&J("1.9.1");F&&J("9");function Ja(a,b){var c;c=a.className;c=u(c)&&c.match(/\S+/g)||[];for(var d=sa(arguments,1),f=c.length+d.length,e=c,g=0;g<d.length;g++)0<=ma(e,d[g])||e.push(d[g]);a.className=c.join(" ");return c.length==f};function Ka(a,b){for(var c in a)b.call(h,a[c],c,a)}function La(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ma(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Oa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Na.length;e++)c=Na[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Pa(a,b){Ka(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Qa?a.setAttribute(Qa[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})}var Qa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function K(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!Ia&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',ga(g.name),'"');if(g.type){e.push(' type="',ga(g.type),'"');var k={};Oa(k,g);g=k;delete g.type}e.push(">");e=e.join("")}e=f.createElement(e);g&&(u(g)?e.className=g:"array"==s(g)?Ja.apply(j,[e].concat(g)):Pa(e,g));2<d.length&&Ra(f,e,d);return e}
function Ra(a,b,c){function d(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];t(e)&&!(aa(e)&&0<e.nodeType)?na(Sa(e)?ra(e):e,d):d(e)}}function Ta(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Sa(a){if(a&&"number"==typeof a.length){if(aa(a))return"function"==typeof a.item||"string"==typeof a.item;if(v(a))return"function"==typeof a.item}return l};function Ua(a){if("function"==typeof a.f)return a.f();if(u(a))return a.split("");if(t(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return La(a)}function Va(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(t(a)||u(a))na(a,b,c);else{var d;if("function"==typeof a.j)d=a.j();else if("function"!=typeof a.f)if(t(a)||u(a)){d=[];for(var f=a.length,e=0;e<f;e++)d.push(e)}else d=Ma(a);else d=h;for(var f=Ua(a),e=f.length,g=0;g<e;g++)b.call(c,f[g],d&&d[g],a)}};function Wa(a,b){this.g={};this.c=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Wa?(c=a.j(),d=a.f()):(c=Ma(a),d=La(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}n=Wa.prototype;n.a=0;n.f=function(){Xa(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.g[this.c[b]]);return a};n.j=function(){Xa(this);return this.c.concat()};n.o=function(a){return L(this.g,a)};
n.remove=function(a){return L(this.g,a)?(delete this.g[a],this.a--,this.c.length>2*this.a&&Xa(this),i):l};function Xa(a){if(a.a!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];L(a.g,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.a!=a.c.length){for(var f={},c=b=0;b<a.c.length;)d=a.c[b],L(f,d)||(a.c[c++]=d,f[d]=1),b++;a.c.length=c}}n.get=function(a,b){return L(this.g,a)?this.g[a]:b};n.set=function(a,b){L(this.g,a)||(this.a++,this.c.push(a));this.g[a]=b};n.n=function(){return new Wa(this)};
function L(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ya(a){var b=a.type;if(b===h)return j;switch(b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:j;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:j;case "select-multiple":for(var b=[],c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:j;default:return a.value!==h?a.value:j}};!F||Ha();var Za=!F||Ha(),$a=F&&!J("8");!H||J("528");G&&J("1.9b")||F&&J("8")||ya&&J("9.5")||H&&J("528");G&&!J("8")||F&&J("9");function ab(){}ab.prototype.Q=l;ab.prototype.u=function(){this.Q||(this.Q=i,this.v())};ab.prototype.v=function(){this.ga&&bb.apply(j,this.ga);if(this.U)for(;this.U.length;)this.U.shift()()};function bb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];t(d)?bb.apply(j,d):d&&"function"==typeof d.u&&d.u()}};function M(a,b){this.type=a;this.currentTarget=this.target=b}A(M,ab);M.prototype.v=function(){delete this.type;delete this.target;delete this.currentTarget};M.prototype.I=l;M.prototype.defaultPrevented=l;M.prototype.preventDefault=function(){this.defaultPrevented=i};function cb(a){cb[" "](a);return a}cb[" "]=r;function N(a,b){a&&this.z(a,b)}A(N,M);n=N.prototype;n.target=j;n.relatedTarget=j;n.offsetX=0;n.offsetY=0;n.clientX=0;n.clientY=0;n.screenX=0;n.screenY=0;n.button=0;n.keyCode=0;n.charCode=0;n.ctrlKey=l;n.altKey=l;n.shiftKey=l;n.metaKey=l;n.H=j;
n.z=function(a,b){var c=this.type=a.type;M.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(G){var f;a:{try{cb(d.nodeName);f=i;break a}catch(e){}f=l}f||(d=j)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=H||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=H||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.H=a;a.defaultPrevented&&this.preventDefault();delete this.I};
n.preventDefault=function(){N.Z.preventDefault.call(this);var a=this.H;if(a.preventDefault)a.preventDefault();else if(a.returnValue=l,$a)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};n.v=function(){N.Z.v.call(this);this.relatedTarget=this.currentTarget=this.target=this.H=j};function db(){}var eb=0;n=db.prototype;n.key=0;n.k=l;n.N=l;n.z=function(a,b,c,d,f,e){if(v(a))this.S=i;else if(a&&a.handleEvent&&v(a.handleEvent))this.S=l;else throw Error("Invalid listener argument");this.A=a;this.W=b;this.src=c;this.type=d;this.capture=!!f;this.R=e;this.N=l;this.key=++eb;this.k=l};n.handleEvent=function(a){return this.S?this.A.call(this.R||this.src,a):this.A.handleEvent.call(this.A,a)};var O={},Q={},R={},S={};
function fb(a,b,c,d,f){if(b)if("array"==s(b))for(var e=0;e<b.length;e++)fb(a,b[e],c,d,f);else{var d=!!d,g=Q;b in g||(g[b]={a:0,i:0});g=g[b];d in g||(g[d]={a:0,i:0},g.a++);var g=g[d],k=a[x]||(a[x]=++ba),m;g.i++;if(g[k]){m=g[k];for(e=0;e<m.length;e++)if(g=m[e],g.A==c&&g.R==f){if(g.k)break;return}}else m=g[k]=[],g.a++;e=gb();e.src=a;g=new db;g.z(c,e,a,b,d,f);c=g.key;e.key=c;m.push(g);O[c]=g;R[k]||(R[k]=[]);R[k].push(g);a.addEventListener?(a==q||!a.ea)&&a.addEventListener(b,e,d):a.attachEvent(b in S?
S[b]:S[b]="on"+b,e)}else throw Error("Invalid event type");}function gb(){var a=hb,b=Za?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}function ib(a,b,c,d){if(!d.B&&d.T){for(var f=0,e=0;f<d.length;f++)d[f].k?d[f].W.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.T=l;0==e&&(delete Q[a][b][c],Q[a][b].a--,0==Q[a][b].a&&(delete Q[a][b],Q[a].a--),0==Q[a].a&&delete Q[a])}}
function jb(a,b,c,d,f){var e=1,b=b[x]||(b[x]=++ba);if(a[b]){a.i--;a=a[b];a.B?a.B++:a.B=1;try{for(var g=a.length,k=0;k<g;k++){var m=a[k];m&&!m.k&&(e&=kb(m,f)!==l)}}finally{a.B--,ib(c,d,b,a)}}return Boolean(e)}
function kb(a,b){if(a.N){var c=a.key;if(O[c]){var d=O[c];if(!d.k){var f=d.src,e=d.type,g=d.W,k=d.capture;f.removeEventListener?(f==q||!f.ea)&&f.removeEventListener(e,g,k):f.detachEvent&&f.detachEvent(e in S?S[e]:S[e]="on"+e,g);f=f[x]||(f[x]=++ba);g=Q[e][k][f];if(R[f]){var m=R[f],p=ma(m,d);0<=p&&C.splice.call(m,p,1);0==m.length&&delete R[f]}d.k=i;g.T=i;ib(e,k,f,g);delete O[c]}}}return a.handleEvent(b)}
function hb(a,b){if(!O[a])return i;var c=O[a],d=c.type,f=Q;if(!(d in f))return i;var f=f[d],e,g;if(!Za){var k;if(!(k=b))a:{k=["window","event"];for(var m=q;e=k.shift();)if(m[e]!=j)m=m[e];else{k=j;break a}k=m}e=k;k=i in f;m=l in f;if(k){if(0>e.keyCode||e.returnValue!=h)return i;a:{var p=l;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(w){p=i}if(p||e.returnValue==h)e.returnValue=i}}p=new N;p.z(e,this);e=i;try{if(k){for(var o=[],fa=p.currentTarget;fa;fa=fa.parentNode)o.push(fa);g=f[i];g.i=g.a;for(var z=
o.length-1;!p.I&&0<=z&&g.i;z--)p.currentTarget=o[z],e&=jb(g,o[z],d,i,p);if(m){g=f[l];g.i=g.a;for(z=0;!p.I&&z<o.length&&g.i;z++)p.currentTarget=o[z],e&=jb(g,o[z],d,l,p)}}else e=kb(c,p)}finally{o&&(o.length=0),p.u()}return e}d=new N(b,this);try{e=kb(c,d)}finally{d.u()}return e};function lb(a){this.P=a;this.X=u("searchForm")?document.getElementById("searchForm"):"searchForm";this.ma=u("tagsInput")?document.getElementById("tagsInput"):"tagsInput";this.F=u("resultDiv")?document.getElementById("resultDiv"):"resultDiv";fb(this.X,"submit",this.la,l,this)}lb.prototype.la=function(a){a.preventDefault();mb(this.P)};lb.prototype.update=function(a){a=oa(a.items,this.da);Ta(this.F);na(a,function(a){this.F.appendChild(a)},this)};
lb.prototype.da=function(a){return K("div",{"class":"item"},K("a",{href:a.link},K("h3",{"class":"itemTitle"},a.title)),K("p",{"class":"itemAuthor"},a.author),K("a",{href:a.link},K("img",{"class":"itemImage",src:a.media.m})),K("hr"))};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function nb(a,b){this.t=[];this.fa=b||j}n=nb.prototype;n.q=l;n.r=l;n.s=0;n.Y=l;n.ba=l;n.$=0;n.O=function(a,b){ob(this,a,b);this.s--;0==this.s&&this.q&&pb(this)};function ob(a,b,c){a.q=i;a.J=c;a.r=!b;pb(a)}function qb(a){if(a.q){if(!a.Y)throw new rb;a.Y=l}}function sb(a,b,c,d){a.t.push([b,c,d]);a.q&&pb(a)}function tb(a){return pa(a.t,function(a){return v(a[1])})}
function pb(a){a.M&&(a.q&&tb(a))&&(q.clearTimeout(a.M),delete a.M);a.V&&(a.V.$--,delete a.V);for(var b=a.J,c=l,d=l;a.t.length&&0==a.s;){var f=a.t.shift(),e=f[0],g=f[1],f=f[2];if(e=a.r?g:e)try{var k=e.call(f||a.fa,b);k!==h&&(a.r=a.r&&(k==b||k instanceof Error),a.J=b=k);b instanceof nb&&(d=i,a.s++)}catch(m){b=m,a.r=i,tb(a)||(c=i)}}a.J=b;d&&a.s&&(sb(b,y(a.O,a,i),y(a.O,a,l)),b.ba=i);c&&(a.M=q.setTimeout(function(){throw new ub(b);},0))}function rb(){B.call(this)}A(rb,B);rb.prototype.message="Already called";
function ub(a){B.call(this);this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}A(ub,B);function vb(a,b){var c=b||{},d=c.document||document,f=document.createElement("SCRIPT"),e={qa:f,L:h},g=new nb(0,e),k=j,m=c.timeout!=j?c.timeout:5E3;0<m&&(k=window.setTimeout(function(){wb(f,i);var b=new xb(yb,"Timeout reached for loading script "+a);qb(g);ob(g,l,b)},m),e.L=k);f.onload=f.onreadystatechange=function(){if(!f.readyState||f.readyState=="loaded"||f.readyState=="complete"){wb(f,c.ca||l,k);qb(g);ob(g,i,j)}};f.onerror=function(){wb(f,i,k);var b=new xb(zb,"Error while loading script "+a);qb(g);
ob(g,l,b)};Pa(f,{type:"text/javascript",charset:"UTF-8",src:a});Ab(d).appendChild(f);return g}function Ab(a){var b=a.getElementsByTagName("HEAD");return!b||0==b.length?a.documentElement:b[0]}function wb(a,b,c){c!=j&&q.clearTimeout(c);a.onload=r;a.onerror=r;a.onreadystatechange=r;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var zb=0,yb=1;function xb(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);B.call(this,c);this.code=a}A(xb,B);var Bb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Cb(a,b){var c;if(a instanceof Cb)this.e=b!==h?b:a.e,Db(this,a.l),c=a.G,T(this),this.G=c,c=a.p,T(this),this.p=c,Eb(this,a.D),c=a.C,T(this),this.C=c,Fb(this,a.h.n()),c=a.w,T(this),this.w=c;else if(a&&(c=(""+a).match(Bb))){this.e=!!b;Db(this,c[1]||"",i);var d=c[2]||"";T(this);this.G=d?decodeURIComponent(d):"";d=c[3]||"";T(this);this.p=d?decodeURIComponent(d):"";Eb(this,c[4]);d=c[5]||"";T(this);this.C=d?decodeURIComponent(d):"";Fb(this,c[6]||"",i);c=c[7]||"";T(this);this.w=c?decodeURIComponent(c):
""}else this.e=!!b,this.h=new U(j,0,this.e)}n=Cb.prototype;n.l="";n.G="";n.p="";n.D=j;n.C="";n.w="";n.ha=l;n.e=l;n.toString=function(){var a=[],b=this.l;b&&a.push(V(b,Gb),":");if(b=this.p){a.push("//");var c=this.G;c&&a.push(V(c,Gb),"@");a.push(encodeURIComponent(""+b));b=this.D;b!=j&&a.push(":",""+b)}if(b=this.C)this.p&&"/"!=b.charAt(0)&&a.push("/"),a.push(V(b,"/"==b.charAt(0)?Hb:Ib));(b=this.h.toString())&&a.push("?",b);(b=this.w)&&a.push("#",V(b,Jb));return a.join("")};n.n=function(){return new Cb(this)};
function Db(a,b,c){T(a);a.l=c?b?decodeURIComponent(b):"":b;a.l&&(a.l=a.l.replace(/:$/,""))}function Eb(a,b){T(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.D=b}else a.D=j}function Fb(a,b,c){T(a);b instanceof U?(a.h=b,a.h.K(a.e)):(c||(b=V(b,Kb)),a.h=new U(b,0,a.e))}function Lb(a,b,c){T(a);"array"==s(c)||(c=[""+c]);Mb(a.h,b,c)}function T(a){if(a.ha)throw Error("Tried to modify a read-only Uri");}n.K=function(a){this.e=a;this.h&&this.h.K(a);return this};
function V(a,b){return u(a)?encodeURI(a).replace(b,Nb):j}function Nb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Gb=/[#\/\?@]/g,Ib=/[\#\?:]/g,Hb=/[\#\?]/g,Kb=/[\#\?@]/g,Jb=/#/g;function U(a,b,c){this.d=a||j;this.e=!!c}
function W(a){if(!a.b&&(a.b=new Wa,a.a=0,a.d))for(var b=a.d.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=j,e=j;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=X(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}n=U.prototype;n.b=j;n.a=j;n.add=function(a,b){W(this);this.d=j;var a=X(this,a),c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.a++;return this};
n.remove=function(a){W(this);a=X(this,a);return this.b.o(a)?(this.d=j,this.a-=this.b.get(a).length,this.b.remove(a)):l};n.o=function(a){W(this);a=X(this,a);return this.b.o(a)};n.j=function(){W(this);for(var a=this.b.f(),b=this.b.j(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};n.f=function(a){W(this);var b=[];if(a)this.o(a)&&(b=qa(b,this.b.get(X(this,a))));else for(var a=this.b.f(),c=0;c<a.length;c++)b=qa(b,a[c]);return b};
n.set=function(a,b){W(this);this.d=j;a=X(this,a);this.o(a)&&(this.a-=this.b.get(a).length);this.b.set(a,[b]);this.a++;return this};n.get=function(a,b){var c=a?this.f(a):[];return 0<c.length?c[0]:b};function Mb(a,b,c){a.remove(b);0<c.length&&(a.d=j,a.b.set(X(a,b),ra(c)),a.a+=c.length)}
n.toString=function(){if(this.d)return this.d;if(!this.b)return"";for(var a=[],b=this.b.j(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(""+d),d=this.f(d),e=0;e<d.length;e++){var g=f;""!==d[e]&&(g+="="+encodeURIComponent(""+d[e]));a.push(g)}return this.d=a.join("&")};n.n=function(){var a=new U;a.d=this.d;this.b&&(a.b=this.b.n());return a};function X(a,b){var c=""+b;a.e&&(c=c.toLowerCase());return c}
n.K=function(a){a&&!this.e&&(W(this),this.d=j,Va(this.b,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),Mb(this,d,a))},this));this.e=a};function Ob(a,b){this.na=new Cb(a);this.aa=b?b:"callback";this.L=5E3}var Pb=0;Ob.prototype.send=function(a,b,c,d){a=a||j;d=d||"_"+(Pb++).toString(36)+ea().toString(36);q._callbacks_||(q._callbacks_={});var f=this.na.n();if(a)for(var e in a)(!a.hasOwnProperty||a.hasOwnProperty(e))&&Lb(f,e,a[e]);b&&(q._callbacks_[d]=Qb(d,b),Lb(f,this.aa,"_callbacks_."+d));b=vb(f.toString(),{timeout:this.L,ca:i});sb(b,j,Rb(d,a,c),h);return{pa:d,oa:b}};function Rb(a,b,c){return function(){Sb(a,l);c&&c(b)}}
function Qb(a,b){return function(c){Sb(a,i);b.apply(h,arguments)}}function Sb(a,b){q._callbacks_[a]&&(b?delete q._callbacks_[a]:q._callbacks_[a]=r)};function Tb(){this.view=new lb(this);this.ia=new Ob(this.view.X.getAttribute("action"),"jsoncallback");mb(this)}function mb(a){var b={format:"json",tags:Ya(a.view.ma).split(/\s+/).join(",")},c=a.view;Ta(c.F);var c=c.F,d=K("p",j,"Searching public Flickr feed...");c.appendChild(d);a.ia.send(b,y(a.ka,a),y(a.ja,a))}Tb.prototype.ka=function(a){this.view.update(a)};Tb.prototype.ja=function(a){console.log("error",a)};function Ub(){window.P=new Tb}var Y=["demo","initialize"],Z=q;!(Y[0]in Z)&&Z.execScript&&Z.execScript("var "+Y[0]);for(var $;Y.length&&($=Y.shift());)!Y.length&&Ub!==h?Z[$]=Ub:Z=Z[$]?Z[$]:Z[$]={};
//@ sourceMappingURL=C:\Code\github\GoogleClosure.NET\GoogleClosure.Demo\Scripts\demo.js.map
