// This file was autogenerated by 'devenv.exe'
// Please do not edit.
goog.addDependency('../../../demo/Controller.js', ['demo.Controller'], ['demo.View', 'goog.events', 'goog.net.Jsonp']);
goog.addDependency('../../../demo/demo.js', ['demo'], ['demo.Controller']);
goog.addDependency('../../../demo/View.js', ['demo.View'], ['goog.dom', 'goog.dom.forms', 'goog.events', 'goog.events.EventType', 'goog.string']);
